# Generated by Django 4.1.4 on 2023-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librariesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='added',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
