# Generated by Django 4.1.4 on 2023-01-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hero',
            field=models.ImageField(blank=True, default='hero_default.jpg', null=True, upload_to='course_hero'),
        ),
    ]
